### ISSUE TITLE
URLs build inside custom popups not working

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/information-lookup#12]
When using the information lookup combined popup functionality, URLs are not being generated correctly from a custom popup authored from a webmap.

URL Example: http://map1.msc.fema.gov/bundle/{FIRMPANEL}.zip

URL from webmap - 
![webmappopup](https://cloud.githubusercontent.com/assets/5614261/3850597/932f9e36-1e87-11e4-9183-6fd8629d3a74.jpg)

URL from information lookup - 
![infopopup](https://cloud.githubusercontent.com/assets/5614261/3850567/43607286-1e87-11e4-901c-8c213ff71c0e.jpg)

**Comment by rrmoore** [comment]
I found that the field reference was case sensitive.
