### ISSUE TITLE
Error handling: Unable to display results if image in pop-up unavailable

### ISSUE THREAD

**Issue by clareprice** [Esri/information-lookup#13]
If an image, set in the web map's pop-up media, becomes unavailable, the app will linger when querying a location with this pop-up image. Ideally, an image should not be unavailable however would it be possible to still have the pop-up display with the image unavailable icon, like what happens in the web map?
![image](https://cloud.githubusercontent.com/assets/5611508/4168012/f45d8f3c-3517-11e4-9666-97295b09f29b.png)

**Comment by MikeMillerGIS** [comment]
No workaround, closing
