### ISSUE TITLE
Popup URL Links not formatting correctly

### ISSUE THREAD

**Issue by nelsm** [Esri/information-lookup#19]
I'm having a problem getting links I have configured on my map to show properly when used in the template. Everything else works great.  I tried several and no luck. See image below. 
![image](https://cloud.githubusercontent.com/assets/12068793/7275995/d45ca9c2-e8bb-11e4-81bd-c97e7c520c67.png)

Here is a link to the map I am using for popups, maybe it has something to do with the way I configured them?:
http://arcg.is/1PhUvW9

**Comment by MikeMillerGIS** [comment]
I cannot view how you set up the pop ups, would you be able to share the pop up info?

**Comment by nelsm** [comment]
Thanks for looking at this. I'm using the custom attribute display:
![image](https://cloud.githubusercontent.com/assets/12068793/7276496/c7b37022-e8be-11e4-8390-7fd2b65ff742.png)
![image](https://cloud.githubusercontent.com/assets/12068793/7276523/f4e2e488-e8be-11e4-9c43-a0a052b00ed3.png)

**Comment by MikeMillerGIS** [comment]
I was able to reproduce, it looks like a bug.  The work around for now is just use the field in the pop up, and not define it as a link.

**Comment by nelsm** [comment]
OK thanks. bummer. Would have been perfect with the links.

**Comment by MikeMillerGIS** [comment]
It still can work for you, use this format for your pop up
For {distribution.BOUNDARY.COMDIST_LOOKUP.URL1}

will produce this in the popup
![image](https://cloud.githubusercontent.com/assets/2707285/7276661/444eea16-e8d9-11e4-9cce-b9072aa30f7e.png)

**Comment by nelsm** [comment]
OK. Will give that a shot. Thanks.

**Comment by MikeMillerGIS** [comment]
Reopening as it is a bug, will close once resolved
