### ISSUE TITLE
Infowindow is underneath Address bar and basemap widget on maximizing

### ISSUE THREAD

**Issue by skrishn** [Esri/information-lookup#21]
Steps to repro
1. Click on a feature and maximize the infowindow
2. Notice the Maximized infowindow is beneath Address Bar and basemap widget, hence the infowindow Title bar information will not be visible
.
![infolookup_infowindowmaximizeissue](https://cloud.githubusercontent.com/assets/3836616/7868118/b72aa694-052e-11e5-913e-4736a63042ed.PNG)

This behavior is seen in the production and devext apps.

**Comment by MikeMillerGIS** [comment]
resolved
