### ISSUE TITLE
Share link button opens the app in a new tab

### ISSUE THREAD

**Issue by GISTiger** [Esri/information-lookup#44]
I'm using this template through AGOL (created a web map and shared it using the Information Lookup template). The link button at the bottom of the docked pop-up does not offer sharing options. Clicking it results in the same web app opening in a new tab.

**Comment by ladeef** [comment]
Same for me, however if you notice the new address in the bar is the populated link to share.  It's a bit weird.

**Comment by MikeMillerGIS** [comment]
That is how it is currently designed.  It generates a unique url.

**Comment by GISTiger** [comment]
I didn't catch that the new link did an autozoom to the current location, so that definitely makes a difference. I was expecting to get a box with a URL that I could copy/paste.
