### ISSUE TITLE
Crashes on mobile

### ISSUE THREAD

**Issue by ladeef** [Esri/information-lookup#45]
Chrome and Safari crashes on a mobile device when trying to query a location.

**Comment by MikeMillerGIS** [comment]
Can you provide the exact steps?  Do you mean clicking on the map, using the GPS button, or entering a search value?

**Comment by ladeef** [comment]
It happens when a search is done form the search bar.  The pop-up fails to load and page crashes.  You can test my app at gis.atlantaga.gov Property Info.
Only seems.to happen on mobile devices

**Comment by ladeef** [comment]
Strangely enough, it seems to be working now on Android, chrome.

**Comment by MikeMillerGIS** [comment]
Just tried 885 Thurmond St on my andriod, worked fine, let me get some other devices and see if I can repo.  Do you know if there was a particular address that was causing it?

**Comment by MikeMillerGIS** [comment]
closing until we can build a repo case
