### ISSUE TITLE
Geonet - information lookup template search issue

### ISSUE THREAD

**Issue by clareprice** [Esri/information-lookup#48]
@MikeMillerGIS 

https://geonet.esri.com/thread/187288-information-lookup-template-search-issue

**Comment by MikeMillerGIS** [comment]
##Notes for release##
- 4 new options added to configuration panel
   - minLineSize - The minimum size of the overlap of linesin the results.  Only valid when checksize is enabled
   - minPolygonSize - TThe minimum size of the overlap of polygons in the results.  Only valid when checksize is enabled
   - checkSize - Check the amount of overlap of the searched results from the lookup layer with the search features geometry
   - onlySearchFeature - Only include the search feature in the results if the search layer is included in the lookup layers.

**Comment by MikeMillerGIS** [comment]
@iwittenmyer for 5.1
