### ISSUE TITLE
Not able to add custom locators

### ISSUE THREAD

**Issue by ladeef** [Esri/information-lookup#56]
My Organizational locators aren't showing up in the ArcGIS Online version of the application.  Under the Search Settings, only ESRI World Locator.

**Comment by MikeMillerGIS** [comment]
Could you please log a tech support incident.  They will be able to help trouble shoot this issue.  We are using the ArcGIS Online framework to get this information.  It is not in the app itself.

**Comment by ladeef** [comment]
will do, thanks

**Comment by MikeMillerGIS** [comment]
I did test real quick, I was able to get a public custom locator working:
![image](https://user-images.githubusercontent.com/2707285/30916647-e61fa29a-a367-11e7-9e27-be09e77e6f88.png)

I do modify my above comment, there is code in the app to retrieve the orgs locators.  I was thinking about the geocode settings in the configuration, which this app does not us.

**Comment by MikeMillerGIS** [comment]
@ladeef revised comments.

**Comment by MikeMillerGIS** [comment]
Also, are there any errors or warnings on your console?  My only guess is somehow, the app is not retrieving the locator info correctly.  Tech support can help you hunt this down.

**Comment by ladeef** [comment]
Just got off the phone with tech support, turns out I needed the "geosearch" option checked on the the locator settings.
