### ISSUE TITLE
Enhancement Request - Add other geometry types to intersect workflow

### ISSUE THREAD

**Issue by busbus** [Esri/information-lookup#7]
As a citizen, I need to search for my parcel (or a parcel that I’m thinking about purchasing) by address or parcel number and select it on the map.  From that selected parcel, I need to find out if it is in the floodplain (intersected feature).  
                
- Current “point” based location not sufficient for reporting – I would think for a very large - maybe not (+- 10 AC) parcel it may also not have utility service where the address lookup is going?
- The improved structure may be out of the floodplain but the parcel inside (future improvements)

Screenshot – these parcels are technically in the floodplain but the address search reports them “not” in the floodplain.

![flood](https://cloud.githubusercontent.com/assets/5614261/3831592/1a5d3eac-1d95-11e4-8881-16670b9540ec.png)

**Comment by MikeMillerGIS** [comment]
@busbus I have implemented this code, if you are still interested in these functions, lets review and make sure what I have added supports your workflow.
