### ISSUE TITLE
Enhancement Request - Specify your own criteria for searching

### ISSUE THREAD

**Issue by busbus** [Esri/information-lookup#9]
Address, POI is great - but what about user specified search options line parcel no., owner name, fire name, etc.

![search](https://cloud.githubusercontent.com/assets/5614261/3849317/e1874350-1e77-11e4-96a8-4369da86adeb.jpg)

The new Basic Viewer does this COTS.

http://www.arcgis.com/apps/Viewer/index.html

**Comment by MikeMillerGIS** [comment]
Search has been updated to handle point layers
